#! /bin/bash

##### Show Colors ls #####

if [[ `uname` == 'Linux' ]]; then
   export LS_OPTS='--color=auto'
fi

##### Baseline exports #####

export dev="$HOME/dev"
export blog="$HOME/blog"
export personal_dev="$dev/tabfugnic"
export dotfiles="$dev/dotfiles"
export tabfugnic_dev="$dev/tabfugnic"
export sapt="sudo apt"

##### Directory Aliases #####

alias blog='cd $blog'
alias dev='cd $dev'
alias dotfiles='cd $dotfiles'
alias tab='cd $tabfugnic_dev'
alias cur='cd $CURRENT_PROJECT_DIR'
alias other='cd $OTHER_PROJECT_DIR'
alias enyc='cd $dev/emacsnyc/emacsnyc.github.io'

##### tar Shortcuts #####

alias tbunzip='tar xvjf'
alias tgunzip='tar xvzf'
alias tun='tar xvf'

##### Aptitude Shortcuts #####

alias sai='$sapt install'
alias saud='$sapt update'
alias sadu='$sapt dist-upgrade'
alias saar='$sapt autoremove'
alias sar='$sapt remove'
alias sac='$sapt clean'
alias saac='$sapt autoclean'
alias cleanup='saar -y && saac && sac'
alias full_update='saud && sadu -y && cleanup'

# Misc Aliases
alias resp=". ~/.bash_profile"
alias ls="ls ${LS_OPTS}"
