#! /bin/bash

########################
#######  System  #######
########################

##### Show Colors ls #####

if [[ `uname` == 'Linux' ]]; then
   export LS_OPTS='--color=auto'
fi

##### Baseline exports #####

export dev="$HOME/dev"
export blog="$personal_dev/personal-blog"
export personal_dev="$dev/tabfugnic"
export dotfiles="$dev/dotfiles"
export thoughtbot_dev="$dev/thoughtbot"
export tabfugnic_dev="$dev/tabfugnic"
export sag="sudo apt-get"

##### Directory Aliases #####

alias blog='cd $blog'
alias dev='cd $dev'
alias dot='cd $dotfiles'
alias tbot='cd $thoughtbot_dev'
alias tab='cd $tabfugnic_dev'
alias cur='cd $CURRENT_PROJECT_DIR'
alias ft='cd $thoughtbot_dev/french_toast'

##### tar Shortcuts #####

alias tbunzip='tar xvjf'
alias tgunzip='tar xvzf'
alias tun='tar xvf'

##### Headless Browser #####

alias headless='xvfb-run --server-args="-screen 0, 1920x1080x24"'

##### Display Shortcuts #####

alias adsp='xrandr --auto'
alias edspoff='xrandr --output eDP1 --off'
alias ldspoff='xrandr --output LVD1 -off'

##### Aptitude Shortcuts #####

alias sag='$sag'
alias sai='$sag install'
alias saud='$sag update'
alias saug='$sag upgrade'
alias sadu='$sag dist-upgrade'
alias saar='$sag autoremove'
alias sar='$sag remove'
alias sac='$sag clean'
alias saac='$sag autoclean'
alias cleanup='saar -y && saac && sac'
alias update='saud && saug -y && cleanup'
alias full-update='saud && sadu -y && cleanup'

##### Flash Updating #####

alias update-flash='sudo update-flashplugin-nonfree --install'

##### Git aliases ######

alias gwin="git shortlog -n -s"
alias gcb="git symbolic-ref HEAD 2>/dev/null | cut -d'/' -f 3"

##### Removal Script #####

alias rmorig='find . -type f -name *.orig -exec rm -f {} \;'

##### Elasticsearch / Kafka #####

alias start_es='sudo -i service elasticsearch start'
alias start_kafka='nohup ~/kafka/bin/kafka-server-start.sh ~/kafka/config/server.properties > ~/kafka/kafka.log 2>&1 &
'
alias restart_es='sudo -i service elasticsearch restart'

# Misc Aliases
alias resp=". ~/.bash_profile"
alias ls="ls ${LS_OPTS}"
alias gpg="gpg2"

######################
#######  Ruby  #######
######################

##### Bundle Exec Stuff #####

alias bx='bundle exec'
alias bspec='bundle exec rspec'

##### Chruby #####

alias chsudo='sudo chruby-exec `ruby --version | grep "ruby [^ ]"` --'
