#! /bin/bash

dotfiles=dirname `pwd`/.. &> /dev/null

echo "Prepare dotfiles"
rm -rf $HOME/.emacs.d &> /dev/null || true
rm -rf $HOME/.i3 &> /dev/null || true
rm -rf $HOME/.bash &> /dev/null || true
rm -rf $HOME/.config/i3status &> /dev/null || true

mkdir $HOME/bin &> /dev/null || true
mkdir $HOME/.offlineimap >& /dev/null || true

echo "Link up dotfiles"
ln -fs $dotfiles/bashrc $HOME/.bashrc
ln -fs $dotfiles/aliases $HOME/.aliases
ln -fs $dotfiles/bash_profile $HOME/.bash_profile
ln -fs $dotfiles/bash $HOME/.bash
ln -fs $dotfiles/emacs $HOME/.emacs
ln -fs $dotfiles/emacs.d/ $HOME/.emacs.d
ln -fs $dotfiles/i3/ $HOME/.i3
ln -fs $dotfiles/config/i3status $HOME/.config/i3status
ln -fs $dotfiles/offlineimaprc $HOME/.offlineimaprc
ln -fs $dotfiles/offlineimap/config.py $HOME/.offlineimap/config.py
ln -fs $dotfiles/bin/stop_rsi $HOME/bin/stop_rsi
ln -fs $dotfiles/bin/i3exit $HOME/bin/i3exit
ln -fs $dotfiles/bin/setup_terminals $HOME/bin/setup_terminals
